title: Espaço gamer
author: Elivelton Rodirgues
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Nesse espaço dedicado aos gamers,recheado de informações e novidades do mundo dos jogos. Fça parte desse espaço também.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will faila
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
